language: node_js
node_js:
  - "5.1"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
#  - "0.8"
#  - "0.6"
  - "iojs"
matrix:
  allow_failures:
    - node_js:"4.1"
    - node_js:"4.0"
#    - node_js:"0.8"
#    - node_js:"0.6"
    - node_js:"iojs"
  fast_finish: true
script: "if [[ $TRAVIS_NODE_VERSION=='5.1' ]]; then npm install coveralls@2 istanbul@0.4 && npm run test-travis-cov; else npm run test-travis; fi"
after_script: "if [[ $TRAVIS_NODE_VERSION=='5.1' ]]; then cat ./coverage/lcov.info | coveralls; fi"
sudo: false
